* 今日计划

** 完成C++图像算法的编写,以及命令行工具的编写

* 今日收获

** 置乱算法 

@@html:&ensp;&ensp;@@ 置乱算法在图像隐藏中拥有重要的作用：

+ 使机密图像变得杂乱无章，类似随机噪声，提高载体图像的隐蔽性。
+ 保证即使隐藏算法被破解，提取的置乱图不经逆置乱破译也毫无意义
+ 载体图像如遭到恶意攻击，提取图像进行逆置乱时，受攻击之处往往被分散到机密图各处，从而提高机密图的可识别
性。

*** 基于几何变换的置乱方法

**** 猫脸算法(Arnold算法)

*** 基于分形的置乱方法
**** 基于Hibert曲线的置乱算法

***  基于DES的置乱算法
***  基于幻方的置乱算法
***  基于生命游戏的置乱算法
***  基于骑士巡游的置乱算法
***  随机序列算法
    
***  Logisticy映射的置乱算法

@@html:&ensp;&ensp;@@ 一维Logistic映射来源于混沌力学的虫口模型，迭代公式为:

\begin{equation}
x_{i+1} = \mu x_i(1-x_i) 
\end{equation}

当 $3.5699456 < \mu \leq 4$ 时, Logistic 映射处于混沌状态，其产生的序列是非周期的，不收敛的，当

$x_i \subseteq (0,1)$ 时Logistic映射也落在 $(0,1)$ 范围内， $\mu \leq 3.5699456$ 或 $\mu > 4$ ,生成
的序列必将收敛于某个特定的值。

    
**** Logistic算法实现

（1） 将大小为 $m$ 行和 $n$ 列的图像转换成一维序列 $A(a_1,a2,....a_{mxn})$ ;

（2） 设定 $x_0 \subset (0,1), \mu \subset (3.5699456,4)$ , 产生一长度为 $mxn$ 的随机
不重复序列 $(b_1,b_2,....,b_{mxn})$，对该序列进行升序排序得到序列 $C(c_1,c_2,....,c_{mxn});

（3） 创建一个空序列 $D(d_1,d_2,....,d_{mxn})$ , 按增序检索B中的每一个元素 $b_i$ 在C中的位置 $j$ , 令 $d_i = a_j$, 这样 $D$ 为 $A$ 的置乱序列。

（4）  将序列 $D$ 转换为 $m$ 行 $n$ 列的二维图像，D 为置乱图像
$x_0$ 和 $\mu$ 是本算法中的两个密钥。 

@@html:&ensp;&ensp;@@ $x_0$ 和 $\mu$ 是本算法的两个密钥。逆置乱解码算法为: 将提取的置乱图像转换成一维序列 $A^{\prime}$ , 用密钥产生序列 $B^{\prime}$ 并按升序排列成序列 $C^{\prime}$ , 检查 $C^{\prime}$ 中每个元素在 $c_i^{\prime}$ 在 $B^{\prime}$ 中的位置 j, 创建
空序列 $D^{\prime}$ 且令 $d_i^{\prime}=a_j^{\prime}$ , $D^{\prime}$ 转换成二维矩阵即恢复原图。










